version: '3.9'
services:
  app:
    build: .
    container_name: test-expo
    ports:
      - "19000:19000"   # Metro Bundler
      - "19001:19001"   # Fast Refresh / Debugger
      - "19002:19002"   # Expo Developer Tools
    volumes:
      - .:/app
    environment:
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
      - EXPO_HOSTNAME=0.0.0.0
    tty: true
