version: '3.9'
services:
  app-build-server:
    build: .
    container_name: test-expo
    ports:
      - "19000:19000"   # Metro Bundler
      - "19001:19001"   # Fast Refresh / Debugger
      - "19002:19002"   # Expo Developer Tools
    volumes:
      - ".:/app"
      - "./node_modules:/app/node_modules"
    environment:
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
      - EXPO_HOSTNAME=0.0.0.0
    tty: true
    stdin_open: true
